In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)

In [ ]:
# Membaca dataset dari file CSV
df = pd.read_csv('cuaca.csv')

# Membagi dataset menjadi fitur (X) dan target (y)
X = df[['Hum', 'Temp']]
y = df['Weather']

# Membagi dataset menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalisasi fitur menggunakan StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Membangun model ANN
model = Sequential()
model.add(Dense(8, input_dim=2, activation='relu'))
model.add(Dense(1, activation='linear'))

# Mengompilasi model
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

# Melatih model
model.fit(X_train_scaled, y_train, epochs=100, batch_size=2, verbose=1)

# Evaluasi model pada data uji
loss, accuracy = model.evaluate(X_test_scaled, y_test)
print(f'\nModel Evaluation - Loss: {loss}, Accuracy: {accuracy}')

# Membuat prediksi
new_data = np.array([[80, 30]])  # Ganti dengan data yang ingin Anda prediksi
new_data_scaled = scaler.transform(new_data)
prediction = model.predict(new_data_scaled)
print(f'\nPrediction for new data: {prediction}')



Epoch 1/100


36/36 [==============================] - 1s 4ms/step - loss: 2422.5403 - accuracy: 0.0141
Epoch 2/100
36/36 [==============================] - 0s 1ms/step - loss: 2404.2893 - accuracy: 0.0141
Epoch 3/100
36/36 [==============================] - 0s 1ms/step - loss: 2385.9453 - accuracy: 0.0141
Epoch 4/100
36/36 [==============================] - 0s 1ms/step - loss: 2366.6357 - accuracy: 0.0141
Epoch 5/100
36/36 [==============================] - 0s 1ms/step - loss: 2347.4250 - accuracy: 0.0141
Epoch 6/100
36/36 [==============================] - 0s 1ms/step - loss: 2327.3271 - accuracy: 0.0141
Epoch 7/100
36/36 [==============================] - 0s 1000us/step - loss: 2307.1240 - accuracy: 0.0141
Epoch 8/100
36/36 [==============================] - 0s 1ms/step - loss: 2284.7644 - accuracy: 0.0141
Epoch 9/100
36/36 [==============================] - 0s 971us/step - loss: 2262.9719 - accuracy: 0.0141
Epoch 10/100
36/36 [==============================] - 0s 971us/step - los

c:\Users\VANZ\Downloads\tubes siscer\.venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [21]:
import pandas as pd
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score
from imblearn.over_sampling import RandomOverSampler
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Membaca dataset dari file CSV
file_path = 'cuaca.csv'
dataset = pd.read_csv(file_path)

# Memilih fitur dan target
X = dataset[['Hum', 'Temp']]
y = dataset['Weather']

# Menggunakan LabelEncoder untuk mengonversi label kategori menjadi bilangan bulat
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Normalisasi fitur menggunakan StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Melakukan oversampling pada seluruh dataset
oversampler = RandomOverSampler(random_state=42)
X_resampled, y_resampled = oversampler.fit_resample(X, y)

# Membagi dataset menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# K-Fold Cross Validation
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
accuracy_scores = []

for train_idx, val_idx in kfold.split(X_train, y_train):
    X_train_fold, X_val_fold = X_train[train_idx], X_train[val_idx]
    y_train_fold, y_val_fold = y_train[train_idx], y_train[val_idx]

    # Membangun model ANN sederhana
    model = keras.Sequential([
        layers.Dense(64, activation='relu', input_shape=(2,)),
        layers.Dense(32, activation='relu'),
        layers.Dense(1, activation='sigmoid')
    ])

    # Kompilasi model
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

    # Melatih model pada data latih fold
    model.fit(X_train_fold, y_train_fold, epochs=10, batch_size=32, validation_data=(X_val_fold, y_val_fold))

    # Evaluasi model pada data uji
    y_pred_fold = model.predict(X_val_fold)
    y_pred_fold_classes = (y_pred_fold > 0.5).astype(int).flatten()
    accuracy_fold = accuracy_score(y_val_fold, y_pred_fold_classes)
    accuracy_scores.append(accuracy_fold)

# Menampilkan rata-rata akurasi dari seluruh fold
average_accuracy = sum(accuracy_scores) / len(accuracy_scores)
print(f'Average Accuracy: {average_accuracy}')


Epoch 1/10
4/4 [==============================] - 1s 49ms/step - loss: 0.6568 - accuracy: 0.1616 - val_loss: 0.5204 - val_accuracy: 0.2000
Epoch 2/10
4/4 [==============================] - 0s 10ms/step - loss: 0.4821 - accuracy: 0.2323 - val_loss: 0.3602 - val_accuracy: 0.2000
Epoch 3/10
4/4 [==============================] - 0s 10ms/step - loss: 0.3214 - accuracy: 0.2323 - val_loss: 0.2039 - val_accuracy: 0.2000
Epoch 4/10
4/4 [==============================] - 0s 9ms/step - loss: 0.1668 - accuracy: 0.2323 - val_loss: 0.0566 - val_accuracy: 0.2000
Epoch 5/10
4/4 [==============================] - 0s 10ms/step - loss: 0.0212 - accuracy: 0.2323 - val_loss: -0.0800 - val_accuracy: 0.2000
Epoch 6/10
4/4 [==============================] - 0s 10ms/step - loss: -0.1107 - accuracy: 0.2323 - val_loss: -0.2199 - val_accuracy: 0.2000
Epoch 7/10
4/4 [==============================] - 0s 11ms/step - loss: -0.2467 - accuracy: 0.2323 - val_loss: -0.3545 - val_accuracy: 0.2000
Epoch 8/10
4/4 [=======

In [41]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Baca dataset dari cuaca.csv
df = pd.read_csv('cuaca.csv')

# Label encoding untuk kolom Hum dan Temp
columns_to_encode = ['Hum', 'Temp']
label_encoder = LabelEncoder()

for column in columns_to_encode:
    df[column] = label_encoder.fit_transform(df[column])

# Menggunakan weather sebagai output
X = df.drop('Weather', axis=1)
y = df['Weather']

# Train test split untuk training dan testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Menormalisasikan dataset
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Inisialisasi model ANN
model = Sequential()
model.add(Dense(64, input_dim=X_train_scaled.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Compile model ANN dengan parameter
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Melatih model ANN
model.fit(X_train_scaled, y_train, epochs=10, batch_size=32, validation_data=(X_test_scaled, y_test))

# Evaluasi model pada set pengujian
y_test_pred_probs = model.predict(X_test_scaled)
y_test_pred = (y_test_pred_probs > 0.5).astype(int)

print("="*50)
print("Classification Report:")
print(classification_report(y_test, y_test_pred, zero_division=1))

# Evaluasi matrix confusion
print("="*50)
conf_matrix = confusion_matrix(y_test, y_test_pred)
print("Confusion Matrix:")
print(conf_matrix)
print("="*50)


Epoch 1/10
3/3 [==============================] - 1s 73ms/step - loss: -0.1432 - accuracy: 0.0141 - val_loss: -3.0178 - val_accuracy: 0.0000e+00
Epoch 2/10
3/3 [==============================] - 0s 14ms/step - loss: -3.3571 - accuracy: 0.0141 - val_loss: -6.7051 - val_accuracy: 0.0000e+00
Epoch 3/10
3/3 [==============================] - 0s 14ms/step - loss: -6.6474 - accuracy: 0.0141 - val_loss: -10.5594 - val_accuracy: 0.0000e+00
Epoch 4/10
3/3 [==============================] - 0s 15ms/step - loss: -9.8558 - accuracy: 0.0141 - val_loss: -14.4303 - val_accuracy: 0.0000e+00
Epoch 5/10
3/3 [==============================] - 0s 14ms/step - loss: -13.1789 - accuracy: 0.0141 - val_loss: -18.2441 - val_accuracy: 0.0000e+00
Epoch 6/10
3/3 [==============================] - 0s 15ms/step - loss: -16.6314 - accuracy: 0.0141 - val_loss: -22.2775 - val_accuracy: 0.0000e+00
Epoch 7/10
3/3 [==============================] - 0s 15ms/step - loss: -20.1583 - accuracy: 0.0141 - val_loss: -26.6651 - va

In [52]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from scikeras.wrappers import KerasClassifier  # Import from scikeras

# Fungsi untuk membuat model
def create_model(optimizer='adam', activation='relu', dropout_rate=0.0):
  model = Sequential()
  model.add(Dense(64, input_dim=X_train_scaled.shape[1], activation=activation))
  model.add(Dropout(dropout_rate))
  model.add(Dense(32, activation=activation))
  model.add(Dense(1, activation='sigmoid'))
  model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
  return model

# Baca dataset dari cuaca.csv
df = pd.read_csv('cuaca.csv')

# Label encoding untuk kolom Hum dan Temp (jika diperlukan)
columns_to_encode = ['Hum', 'Temp']  # Pastikan kolom ini berisi data kategorikal
label_encoder = LabelEncoder()
for column in columns_to_encode:
  df[column] = label_encoder.fit_transform(df[column])

# Menggunakan STATUS sebagai output
X = df.drop('Weather', axis=1)
y = df['Weather']

# Train test split untuk training dan testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Menormalisasikan dataset
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Membuat model dengan KerasClassifier dari scikeras
model = KerasClassifier(build_fn=create_model, epochs=10, batch_size=32, verbose=0, activation='relu')  # Set activation here

# Parameter yang akan dioptimalkan
param_grid = {
  'optimizer': ['adam', 'rmsprop'],
  'activation': ['relu', 'tanh'],
}

# Melakukan Grid Search untuk tuning parameter
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, scoring='accuracy', cv=5)
grid_result = grid_search.fit(X_train_scaled, y_train)

# Menampilkan parameter terbaik
print("Best Parameters:", grid_result.best_params_)

# Menggunakan model terbaik dari Grid Search
best_model = grid_result.best_estimator_

# Evaluasi model sebelum tuning
y_test_pred_before = model.predict(X_test_scaled)
print("="*50)
print("Classification Report (Before Tuning):")
print(classification_report(y_test, y_test_pred_before, zero_division=1))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_before))
print("="*50)

# Evaluasi model setelah tuning
y_test_pred_after = best_model.predict(X_test_scaled)
print("="*50)
print("Classification Report (After Tuning):")
print(classification_report(y_test, y_test_pred_after, zero_division=1))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_after))
print("="*50)


c:\Users\VANZ\Downloads\tubes siscer\.venv\Lib\site-packages\sklearn\model_selection\_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
c:\Users\VANZ\Downloads\tubes siscer\.venv\Lib\site-packages\scikeras\wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
c:\Users\VANZ\Downloads\tubes siscer\.venv\Lib\site-packages\scikeras\wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
c:\Users\VANZ\Downloads\tubes siscer\.venv\Lib\site-packages\scikeras\wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
c:\Users\VA

Best Parameters: {'activation': 'relu', 'optimizer': 'adam'}


NotFittedError: Estimator needs to be fit before `predict` can be called

In [55]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression


# Baca dataset cuaca.csv
df = pd.read_csv('cuaca.csv')

# Pilih kolom Temp dan Hum
X = df[['Temp', 'Hum']]

# Label encoding untuk kolom Weather
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(df['Weather'])

# Train test split untuk training dan testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalisasi dataset
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Buat model
model = LogisticRegression()

# Latih model
model.fit(X_train, y_train)

# Prediksi data uji
y_pred = model.predict(X_test)

# Hitung akurasi
accuracy = accuracy_score(y_test, y_pred)

# Cetak hasil testing
print('Akurasi testing:', accuracy)

# Cetak hasil training
print('Akurasi training:', model.score(X_train, y_train))


Akurasi testing: 0.16666666666666666
Akurasi training: 0.4647887323943662


In [62]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib


# Baca dataset cuaca.csv
df = pd.read_csv('cuaca.csv')

# Pilih kolom Temp dan Hum
X = df[['Temp', 'Hum']]

# Label encoding untuk kolom Weather
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(df['Weather'])

# Train test split untuk training dan testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalisasi dataset
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Buat model
model = SVC()

# Latih model
model.fit(X_train, y_train)

# Prediksi data uji
y_pred = model.predict(X_test)

# Cetak hasil testing
print('Akurasi testing:', accuracy_score(y_test, y_pred))

# Cetak classification report
print('Classification report:\n', classification_report(y_test, y_pred, zero_division=1))

# Cetak confusion matrix
print('Confusion matrix:\n', confusion_matrix(y_test, y_pred))

# Simpan model
joblib.dump(model, 'model.h5')


Akurasi testing: 0.4444444444444444
Classification report:
               precision    recall  f1-score   support

           1       0.50      0.75      0.60         4
           2       0.83      0.45      0.59        11
           3       0.00      0.00      1.00         1
           4       1.00      0.00      0.00         2

    accuracy                           0.44        18
   macro avg       0.58      0.30      0.55        18
weighted avg       0.73      0.44      0.55        18

Confusion matrix:
 [[3 1 0 0]
 [2 5 4 0]
 [1 0 0 0]
 [0 0 2 0]]


['model.h5']